# Generated by Django 3.1.14 on 2024-08-21 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='рус назавние')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='анг назавние')),
                ('title_jp', models.CharField(blank=True, max_length=200, verbose_name='яп назавние')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='изображение покемона')),
                ('description', models.TextField(blank=True, verbose_name='описание покемона')),
                ('previous_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_evolutions', to='pokemon_entities.pokemon', verbose_name='предыдущая эволюция покемона')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='широта')),
                ('longitude', models.FloatField(verbose_name='долгота')),
                ('appeared_at', models.DateTimeField(verbose_name='время появления')),
                ('disappeared_at', models.DateTimeField(verbose_name='время исчезновения')),
                ('level', models.IntegerField(blank=True, verbose_name='уровень')),
                ('health', models.IntegerField(blank=True, verbose_name='здоровье')),
                ('strength', models.IntegerField(blank=True, verbose_name='сила')),
                ('defence', models.IntegerField(blank=True, verbose_name='защита')),
                ('stamina', models.IntegerField(blank=True, verbose_name='выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon', verbose_name='entities')),
            ],
        ),
    ]
