# Generated by Django 3.1.14 on 2024-08-17 11:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_auto_20240817_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание покемона'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='appeared_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 17, 11, 32, 7, 839580, tzinfo=utc), verbose_name='время появления'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='disappeared_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 17, 11, 32, 7, 839580, tzinfo=utc), verbose_name='время исчезновения'),
        ),
    ]
